// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesStageManagerSupinfo.Models;

namespace RazorPagesStageManagerSupinfo.Migrations
{
    [DbContext(typeof(RazorPagesStageContext))]
    [Migration("20190419173526_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("RazorPagesStageManagerSupinfo.Models.Stage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Commentaire");

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("Nombredejour");

                    b.Property<string>("Societe");

                    b.Property<string>("Titre");

                    b.HasKey("ID");

                    b.ToTable("Stage");
                });
#pragma warning restore 612, 618
        }
    }
}
